### ISSUE TITLE
AssertionError: Cannot find installation of real FFmpeg (which comes with ffprobe).

### ISSUE THREAD

**Issue by suhas-goutham** [Deevoluation/ALPR#16]
I get the following error in videosplit_sklearn,py

**Comment by MayankKashyap** [comment]
Hey I want to know, Is this a project for Linux or windows.?

**Comment by Saqhas** [comment]
You have to download this file ffprobe to your system.
It is required for opencv.

**Comment by Siddhant96** [comment]
In line 55: train_set = train_datagen.flow_from_directory('Train',target_size=(64, 64),batch_size=32,class_mode='categorical')
'Train' is the name of the directory which contains the dataset. You need to create this directory at the same location where the code file 'train_detect.py' is present and you need to put your training dataset into it. Same goes for 'Test' as in test dataset. 
I hope this resolves your issue. Feel free to contact further if required. We will try to get back to you as soon as possible.

**Comment by suhas-goutham** [comment]
okay thank you

**Comment by MayankKashyap** [comment]
@Saqhas I already downloaded this file but it again shows the same issue.
