### ISSUE TITLE
model.h5 not present

### ISSUE THREAD

**Issue by angelsingh** [Deevoluation/ALPR#17]
The New_model folder contains the "char-reg.h5" model which we are loading & using. But in "train_detect.py" we are saving the model by naming it "model.h5" & model.h5 is not present.

So, what does **char-reg.h5** contain & where is **model.h5** & are both of them different?

**Comment by Saqhas** [comment]
Actually we changed the name of model.h5 to char-reg.h5. We will change the train_detect.py to avoid confusion.

**Comment by Siddhant96** [comment]
I have commited the required changes. Thanks for pointing out the mistake. Keep contributing.
