### ISSUE TITLE
unable to detect for multiple vehicles.

### ISSUE THREAD

**Issue by santoshmanojbantu** [Deevoluation/ALPR#19]
can we get the code for multiple vehicles per video.....???

**Comment by kaustubhkmr** [comment]
The code is designed to work for the only car at a time. Also, it assumed that the car is in the video. There is no module to detect a car and then launch the model.

**Comment by santoshmanojbantu** [comment]
The code is working fine for single car but not for all the cases. Sometimes i am not able to detect a single car. But my main goal is to detect multiple cars which are in the single video. Can I get the source as where can I find the code??

**Comment by kaustubhkmr** [comment]
There are some constraint to the model like proper lighting, clarity of the video, and last at what angle and distance the video is captured. This few things increase the accuracy of the model. 
You can find many model on github that detects cars like the one using yolo. use this model to detect cars. when the car is captured send the frames to this model to detect the number plate. have a look on this blog to get clear picture https://medium.com/@ablacklama/vehicle-detection-using-yolo-612a3b9b54a9
