### ISSUE TITLE
Issue while executing start.py  (Enter the name of the video:)

### ISSUE THREAD

**Issue by pkmantra** [Deevoluation/ALPR#21]
I am trying to run the start.py
It is asking for input " Enter the name of the video:"
As soon i provide video name (as car6.mp4 ) or left it blank it gives error

Traceback (most recent call last):
  File "Start.py", line 28, in <module>
    (vdolength,totalFrames) = videosplit_sklearn.Launch(name)
NameError: name 'videosplit_sklearn' is not defined

Help me to get it run.

**Comment by harsathAI** [comment]
I am also getting this error. How to solve this?

**Comment by kaustubhkmr** [comment]
Make sure you mention the full path of the video file or read the start.py and modify the video location to suit your req
