### ISSUE TITLE
No module name absl 

### ISSUE THREAD

**Issue by cdpavan** [Deevoluation/ALPR#24]
its getting looped in that error only please help me out ...

**Comment by Saqhas** [comment]
Which script is giving this error. 
Which one are you running.

**Comment by cdpavan** [comment]
I am running Lanch.py

**Comment by cdpavan** [comment]
![no module absl](https://user-images.githubusercontent.com/44666861/67155360-4b101800-f32b-11e9-93b0-06fec7d570fd.PNG)

**Comment by Saqhas** [comment]
Its seems that there is some problem with your tensorflow.
Please uninstall and reinstall the tensorflow
Us this command : pip install tensorflow==1.14.0

Please report back if you find some erroe.

**Comment by Saqhas** [comment]
We have added piplock functionality to the project. Now you won't recieve any library errors
Please follow the setup instructions and inform if any problem
