### ISSUE TITLE
How to detect in video stream?

### ISSUE THREAD

**Issue by yashwant43** [Deevoluation/ALPR#29]

**Comment by Saqhas** [comment]
Sorry for the late reply. The script Start.py is for processing videos only. 
Just go through the readme and the code. You will find what you are looking for. If you still face problem, please reach out to us here

**Comment by Deep-21** [comment]
tensorflow.python.framework.errors_impl.NotFoundError: plate_detector/frozen_inference_graph.pb; No such file or directory::   this issue  will be raising when the  i trying to run  the Start.py  scripts , i hope it will be path problem 
?

**Comment by Saqhas** [comment]
Yes it is a path problem
Run Start.py from the same directory where it is present.
Then this error should not pop

**Comment by Saqhas** [comment]
The model is present in the folder plate_detector at the same level as Start.py.
Check it should be there. Also be sure you have the latest code.

**Comment by Deep-21** [comment]
bro thank u very much , updated latest code working properly with the issue 
,no need switch Start.py to plate_detector folder .

**Comment by Saqhas** [comment]
Closing this issue
