### ISSUE TITLE
Receiving : ValueError: not enough values to unpack (expected 3, got 2)

### ISSUE THREAD

**Issue by thebigshaikh** [Deevoluation/ALPR#31]
**Command Executed:** 
`python Launch.py -i D:\DeavANPR\Examples\frame0.jpg -s False -o D:\DeavANPR\Output -sh False
`
**(frame0.jpg is not changed, the same as repository frame0.jpg in Examples dir)**

**Error : -** 
```
Now we are in the Process of Preprocessing the image
        The image to Grayscale :
        The image to High Contrast:
        The image to Blurred:
        The image thresholded:
Traceback (most recent call last):
  File "Launch.py", line 737, in <module>
    number_plate_text,plate = main(args.ImagePath,args.Save_intermediate,args.output_folder,args.ShowSteps)
  File "Launch.py", line 711, in main
    Refined_plate = detectCharsInPlates(Plates,save_intermediate,output_folder,showSteps)
  File "Launch.py", line 118, in detectCharsInPlates
    listOfPossibleCharsInPlate = findPossibleCharsInPlate(possiblePlate.imgGrayscale, possiblePlate.imgThresh)
  File "Launch.py", line 297, in findPossibleCharsInPlate
    imgContours, contours, npaHierarchy = cv2.findContours(imgThreshCopy, cv2.RETR_LIST, cv2.CHAIN_APPROX_SIMPLE)
ValueError: not enough values to unpack (expected 3, got 2)
```

**Comment by Saqhas** [comment]
What is the version of opencv in your system?
Please follow the versions specified in Pipfile

**Comment by thebigshaikh** [comment]
@Saqhas Yes, I downgraded my packages according to the pip file and the error has gone now. But it's taking a lot of time to execute.
Upon executing I get Tensorflow warnings (which is fine), however, after that, the execution seems to be hung with no output.
Earlier I could see the intermediate images with the following Output: 
`Now we are in the Process of Preprocessing the image
        The image to Grayscale :
        The image to High Contrast:
        The image to Blurred:
        The image thresholded:`

But now I don't, The terminal doesn't op anything( Still running in the background), I waited for around 30 minutes.

**Comment by Saqhas** [comment]
So you mean you are not getting any output

**Comment by thebigshaikh** [comment]
@Saqhas  The execution doesn't complete. No errors, No output. It's still running even after 30 mins

**Comment by thebigshaikh** [comment]
Closing the issue as it was a venv problem. Created a new one and it worked.
