### ISSUE TITLE
Help for api

### ISSUE THREAD

**Issue by premkarki47** [Deevoluation/ALPR#5]
I am Having problem for making api for the following project can you help me for that !! how can i take the dynamic input from the web i.e any video.mp4 file as input and display the result in web i have design the front end in angular 5 
![detect_page](https://user-images.githubusercontent.com/18494873/45338647-f50c6500-b5ad-11e8-9489-223ccff7791d.jpg)

**Comment by Saqhas** [comment]
If the user can select the video file from "Choose file",
Then you just have to pass it to your code to perform whatever task you need to perform.

Now if we take on dynamic input where this app is hosted on the web and some user comes and gives the input as a video. Now what we need to do is send this image to our python script and receive the output in angular and display it. 

The 2 ways to do the python part:
1) Make an api and host it on a server. there is an api code included in the repo. You can change in to work for your code.
2) Make a restful api and use it in the angular js

**Comment by premkarki47** [comment]
i am unable to change that code can you help me to change that😭

**Comment by Saqhas** [comment]
The code is fully written in python using Flask. 
Can you tell why u are facing problem in changing it?
This is a good link for Flask --> https://www.youtube.com/playlist?list=PLQVvvaa0QuDc_owjTbIY4rbgXOFkUYOUB

One personal question? Is this repo so much difficult to understand?
Please, can u give an unbiased feedback about what all things need to be added?

**Comment by premkarki47** [comment]
I want to make this project as web based so that we can give input from web browser and get the result in web page by using API
