### ISSUE TITLE
Optimizer weight shape

### ISSUE THREAD

**Issue by MMaxV** [Deevoluation/ALPR#9]
I tried to run programm, but catcheed the following error

File "D:\Program Files\Python\Python36\lib\site-packages\keras\optimizers.py", line 103, in set_weights
    'provided weight shape ' + str(w.shape))
ValueError: Optimizer weight shape (32,) not compatible with provided weight shape (3, 3, 3, 32)

**Comment by Saqhas** [comment]
What input did u give

**Comment by MMaxV** [comment]
@Saqhas I tried both test video(car6.mp4) and image (OS269DT.jpg) and the same error occured.

**Comment by Saqhas** [comment]
I have dignosed the code. the code seems to work well. Here are the commands u need to write
1) python Start.py
2) Then it will ask for the video, we will provide the video name. Example: car6.mp4
3) Then it will show the result.

Try these steps on your system. If still the same or some new problem occurs please inform us.

We are currently working on adding more content and better documentation to the repo.
If u have any suggestions please feel free to tell us.
